// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("ClientID")]
    public int ClientId { get; set; }

    [Column("TrainerServiceID")]
    public int TrainerServiceId { get; set; }

    [Required]
    [Display(Name = "Дата занятия")]
    public DateTime BookingDateTime { get; set; }

    [Required]
    [Display(Name = "Кол-во занятий")]
    public int SessionsCount { get; set; }

    [Required]
    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Цена за услугу")]
    public decimal UnitPrice { get; set; }

    [Column(TypeName = "decimal(21, 2)")]
    [Display(Name = "Общая стоимость")]
    public decimal? TotalPrice { get; set; }

    [Required]
    [StringLength(20)]
    [Display(Name = "Статус")]
    public string Status { get; set; } = null!;

    [StringLength(500)]
    [Display(Name = "Комментарии")]
    public string? Notes { get; set; }

    [Required]
    [Display(Name = "Дата записи")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Bookings")]
    public virtual Client Client { get; set; } = null!;

    [ForeignKey("TrainerServiceId")]
    [InverseProperty("Bookings")]
    public virtual TrainerService TrainerService { get; set; } = null!;
}