// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Index("Phone", Name = "UQ__Clients__5C7E359E994E93F2", IsUnique = true)]
[Index("Email", Name = "UQ__Clients__A9D10534F7334286", IsUnique = true)]
[Display(Name = "Клиенты")]
public partial class Client
{
    [Key]
    [Column("ClientID")]
    public int ClientId { get; set; }

    [Required(ErrorMessage = "Имя обязательно")]
    [StringLength(100, ErrorMessage = "ФИО должно быть не длиннее 100 символов")]
    [Display(Name = "ФИО")]
    public string FullName { get; set; } = null!;

    [Required(ErrorMessage = "Телефон обязателен")]
    [Phone(ErrorMessage = "Некорректный формат телефона")]
    [RegularExpression(
        @"^(\+7|8)\s?\(?\d{3}\)?[\s-]?\d{3}[\s-]?\d{2}[\s-]?\d{2}$",
        ErrorMessage = "Введите номер в формате +7XXXXXXXXXX или 8 (XXX) XXX-XX-XX"
    )]
    [StringLength(20)]
    [Display(Name = "Телефон")]
    public string Phone { get; set; } = null!;

    [StringLength(100, ErrorMessage = "Email должен быть не длиннее 100 символов")]
    [EmailAddress(ErrorMessage = "Неверный формат email")]
    public string? Email { get; set; }

    [Display(Name = "День рождения")]
    public DateOnly? BirthDate { get; set; }

    [Display(Name = "Дата регистрации")]
    public DateOnly RegistrationDate { get; set; }

    [ScaffoldColumn(false)]
    [ForeignKey("ApplicationUser")]
    public string? ApplicationUserId { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("ClientProfile")]
    public virtual ApplicationUser? ApplicationUser { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("Client")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}