// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Index("Phone", Name = "UQ__Clients__5C7E359E994E93F2", IsUnique = true)]
[Index("Email", Name = "UQ__Clients__A9D10534F7334286", IsUnique = true)]
public partial class Client
{
    [Key]
    [Column("ClientID")]
    public int ClientId { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "ФИО")]
    public string FullName { get; set; } = null!;

    [Required]
    [StringLength(20)]
    [Display(Name = "Телефон")]
    public string Phone { get; set; } = null!;

    [StringLength(100)]
    public string? Email { get; set; }

    [Display(Name = "День рождения")]
    public DateOnly? BirthDate { get; set; }

    [Display(Name = "Дата регистрации")]
    public DateOnly RegistrationDate { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("Client")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}