// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

public partial class FitRazorContext : DbContext
{
    public FitRazorContext(DbContextOptions<FitRazorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<Trainer> Trainers { get; set; }

    public virtual DbSet<TrainerService> TrainerServices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951ACD3650F6F7");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SessionsCount).HasDefaultValue(1);
            entity.Property(e => e.Status).HasDefaultValue("Запланировано");
            entity.Property(e => e.TotalPrice).HasComputedColumnSql("([UnitPrice]*[SessionsCount])", true);

            entity.HasOne(d => d.Client).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__Client__4AB81AF0");

            entity.HasOne(d => d.TrainerService).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__Traine__4BAC3F29");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Clients__E67E1A04E7D74D67");

            entity.Property(e => e.RegistrationDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__Services__C51BB0EAA559C602");
        });

        modelBuilder.Entity<Trainer>(entity =>
        {
            entity.HasKey(e => e.TrainerId).HasName("PK__Trainers__366A1B9C316B4273");
        });

        modelBuilder.Entity<TrainerService>(entity =>
        {
            entity.HasKey(e => e.TrainerServiceId).HasName("PK__TrainerS__16B773266076E5BA");

            entity.HasOne(d => d.Service).WithMany(p => p.TrainerServices).HasConstraintName("FK__TrainerSe__Servi__440B1D61");

            entity.HasOne(d => d.Trainer).WithMany(p => p.TrainerServices).HasConstraintName("FK__TrainerSe__Train__4316F928");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}