// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Display(Name = "Услуги")]
public partial class Service
{
    [Key]
    [Column("ServiceID")]
    public int ServiceId { get; set; }

    [Required(ErrorMessage = "Название обязательно")]
    [StringLength(100)]
    [Display(Name = "Название")]
    public string ServiceName { get; set; } = null!;

    [Required(ErrorMessage = "Продолжительность обязательна")]
    [Display(Name = "Продолжительность, мин")]
    public int DurationMinutes { get; set; }

    [Required(ErrorMessage = "Цена обязательна")]
    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Цена")]
    public decimal BasePrice { get; set; }

    [StringLength(500, ErrorMessage = "Email должен быть не длиннее 500 символов")]
    [Display(Name = "Описание")]
    public string? Description { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("Service")]
    public virtual ICollection<TrainerService> TrainerServices { get; set; } = new List<TrainerService>();
}