// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Index("Phone", Name = "UQ__Trainers__5C7E359ECA461152", IsUnique = true)]
[Index("Email", Name = "UQ__Trainers__A9D10534622E13CC", IsUnique = true)]
public partial class Trainer
{
    [Key]
    [Column("TrainerID")]
    public int TrainerId { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "ФИО")]
    public string FullName { get; set; } = null!;

    [Required]
    [StringLength(20)]
    [Display(Name = "Телефон")]
    public string Phone { get; set; } = null!;

    [Required]
    [StringLength(100)]
    public string Email { get; set; } = null!;

    [StringLength(100)]
    [Display(Name = "Слоган")]
    public string? Slogan { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Специализация")]
    public string Specialization { get; set; } = null!;

    [StringLength(1000)]
    [Display(Name = "Описание специализации")]
    public string? SpecializationDescription { get; set; }

    [StringLength(500)]
    [Display(Name = "Девиз")]
    public string? Motto { get; set; }

    [Required]
    [StringLength(500)]
    [Display(Name = "Образование")]
    public string Education { get; set; } = null!;

    [Required]
    [StringLength(1000)]
    [Display(Name = "Опыт работы")]
    public string WorkExperience { get; set; } = null!;

    [Required]
    [StringLength(1000)]
    [Display(Name = "Достижения")]
    public string SportsAchievements { get; set; } = null!;

    [Required]
    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Зарплата")]
    public decimal Salary { get; set; }

    [StringLength(500)]
    [Display(Name = "Фото")]
    public string? PhotoUrl { get; set; }

    [InverseProperty("Trainer")]
    public virtual ICollection<TrainerService> TrainerServices { get; set; } = new List<TrainerService>();
}