// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Index("TrainerId", "ServiceId", Name = "UQ_TrainerService", IsUnique = true)]
[Display(Name = "Тренеры-Услуги")]
public partial class TrainerService
{
    [Key]
    [Column("TrainerServiceID")]
    public int TrainerServiceId { get; set; }

    [Column("TrainerID")]
    [Display(Name = "Тренер")]
    public int TrainerId { get; set; }

    [Column("ServiceID")]
    [Display(Name = "Услуга")]
    public int ServiceId { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("TrainerService")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ScaffoldColumn(false)]
    [ForeignKey("ServiceId")]
    [InverseProperty("TrainerServices")]
    public virtual Service Service { get; set; } = null!;

    [ScaffoldColumn(false)]
    [ForeignKey("TrainerId")]
    [InverseProperty("TrainerServices")]
    public virtual Trainer Trainer { get; set; } = null!;
}