// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitRazor.Data.Models;

[Index("Phone", Name = "UQ__Trainers__5C7E359ECA461152", IsUnique = true)]
[Index("Email", Name = "UQ__Trainers__A9D10534622E13CC", IsUnique = true)]
[Display(Name = "Тренеры")]
public partial class Trainer
{
    [Key]
    [Column("TrainerID")]
    public int TrainerId { get; set; }

    [Required(ErrorMessage = "ФИО обязательно")]
    [StringLength(100, ErrorMessage = "ФИО должен быть не длиннее 100 символов")]
    [Display(Name = "ФИО")]
    public string FullName { get; set; } = null!;

    [Required(ErrorMessage = "Телефон обязателен")]
    [StringLength(20, ErrorMessage = "Телефон должен быть не длиннее 20 символов")]
    [Display(Name = "Телефон")]
    public string Phone { get; set; } = null!;

    [Required(ErrorMessage = "Email обязателен")]
    [StringLength(100, ErrorMessage = "Email должен быть не длиннее 100 символов")]
    [EmailAddress(ErrorMessage = "Неверный формат email")]
    public string Email { get; set; } = null!;

    [StringLength(100, ErrorMessage = "Слоган должен быть не длиннее 100 символов")]
    [Display(Name = "Слоган")]
    public string? Slogan { get; set; }

    [Required(ErrorMessage = "Специализация обязательна")]
    [StringLength(100, ErrorMessage = "Специализация должна быть не длиннее 100 символов")]
    [Display(Name = "Специализация")]
    public string Specialization { get; set; } = null!;

    [StringLength(1000, ErrorMessage = "Описание должно быть не длиннее 1000 символов")]
    [Display(Name = "Описание специализации")]
    public string? SpecializationDescription { get; set; }

    [StringLength(500, ErrorMessage = "Девиз должен быть не длиннее 500 символов")]
    [Display(Name = "Девиз")]
    public string? Motto { get; set; }

    [Required(ErrorMessage = "Образование обязательно")]
    [StringLength(500, ErrorMessage = "Образование должно быть не длиннее 500 символов")]
    [Display(Name = "Образование")]
    public string Education { get; set; } = null!;

    [Required(ErrorMessage = "Опыт работы обязателен")]
    [StringLength(1000, ErrorMessage = "Опыт работы должен быть не длиннее 1000 символов")]
    [Display(Name = "Опыт работы")]
    public string WorkExperience { get; set; } = null!;

    [Required(ErrorMessage = "Достижения обязательны")]
    [StringLength(1000, ErrorMessage = "Достижения должны быть не длиннее 1000 символов")]
    [Display(Name = "Достижения")]
    public string SportsAchievements { get; set; } = null!;

    [Required(ErrorMessage = "Зарплата обязательна")]
    [Column(TypeName = "decimal(10, 2)")]
    [Display(Name = "Зарплата")]
    public decimal Salary { get; set; }

    [StringLength(500, ErrorMessage = "Путь до фото должно быть не длиннее 500 символов")]
    [Display(Name = "Фото")]
    public string? PhotoUrl { get; set; }

    [ScaffoldColumn(false)]
    [InverseProperty("Trainer")]
    public virtual ICollection<TrainerService> TrainerServices { get; set; } = new List<TrainerService>();
}